### ISSUE TITLE
Temporary removal of REUNION

### ISSUE THREAD

**Issue by ioerror** [katzenpost/katzen#19]
The current katzen client uses two protocols - pandaprime and reunion - however the reunion client isn't the final reunion protocol we published.  Currently the namenlos network has zero reunion providers. Given the state of the network and the state of the protocol implementation, we should disable it for now, and only use pandaprime until we have fully implemented the proper reunion protocol. After that point, we can switch to reunion entirely.

**Comment by leif** [comment]
Reunion is now disabled, as of commits linked to from the corresponding katzenpost issue about this: https://github.com/katzenpost/katzenpost/issues/157
