### ISSUE TITLE
(rename-triggered) panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by leif** [katzenpost/katzen#21]
```
panic: assignment to entry in nil map

goroutine 10 [running]:
github.com/katzenpost/katzenpost/catshadow.(*Client).doSendMessage(0xc000290500, {0xc5, 0x89, 0x65, 0x29}, {0xc0015e44b8, 0x3}, {0xc000eb9f20, 0x9, 0x10})
	github.com/katzenpost/katzenpost@v0.0.20/catshadow/client.go:940 +0x938
github.com/katzenpost/katzenpost/catshadow.(*Client).worker(0xc000290500)
	github.com/katzenpost/katzenpost@v0.0.20/catshadow/worker.go:111 +0x71d
github.com/katzenpost/katzenpost/core/worker.(*Worker).Go.func1()
	github.com/katzenpost/katzenpost@v0.0.20/core/worker/worker.go:39 +0x5a
created by github.com/katzenpost/katzenpost/core/worker.(*Worker).Go
	github.com/katzenpost/katzenpost@v0.0.20/core/worker/worker.go:37 +0xb9
```

steps to reproduce:
1. add new contact
2. before key exchange completes, rename contact
3. after key exchange completes, send a message
4. the above crash occurs
5. after relaunching and trying to message them again: the same crash happens again.

**Comment by leif** [comment]
note: i have not actually tried to reproduce this yet, but the above are the series of steps i took when it happened once.

**Comment by leif** [comment]
update: after receiving a message from the contact, i was able to message them without triggering a crash.

**Comment by mixmasala** [comment]
the rename of contact assigned a map entry for the nickname to nil
