### ISSUE TITLE
document how developers should upgrade dependencies

### ISSUE THREAD

**Issue by leif** [katzenpost/katzen#43]
Docs for people hacking on katzen are in need of lots of work but this ticket is specifically about how the nix `vendorHash` needs to be manually updated whenever anything in `go.mod` changes, as I mentioned in this comment: https://github.com/katzenpost/katzen/pull/38#discussion_r1234002387

This is is the cause of #42 which is blocking #41

**Comment by mixmasala** [comment]
thanks, I'll update that hash
